// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/worker/internal/pkg/domain"
	"sync"
)

// BacklogActionRunnerMock is a mock implementation of runner.BacklogActionRunner.
//
//	func TestSomethingThatUsesBacklogActionRunner(t *testing.T) {
//
//		// make and configure a mocked runner.BacklogActionRunner
//		mockedBacklogActionRunner := &BacklogActionRunnerMock{
//			FeedbackBacklogItemFunc: func(ctx context.Context, projectDir string, item *domain.BacklogItem, message string) error {
//				panic("mock out the FeedbackBacklogItem method")
//			},
//			RecommendWorktreeFunc: func(ctx context.Context, projectDir string, item *domain.BacklogItem) (*domain.Worktree, error) {
//				panic("mock out the RecommendWorktree method")
//			},
//			RefineBacklogItemFunc: func(ctx context.Context, projectDir string, item *domain.BacklogItem) (*domain.BacklogItem, error) {
//				panic("mock out the RefineBacklogItem method")
//			},
//			StartBacklogItemFunc: func(ctx context.Context, projectDir string, item *domain.BacklogItem) error {
//				panic("mock out the StartBacklogItem method")
//			},
//		}
//
//		// use mockedBacklogActionRunner in code that requires runner.BacklogActionRunner
//		// and then make assertions.
//
//	}
type BacklogActionRunnerMock struct {
	// FeedbackBacklogItemFunc mocks the FeedbackBacklogItem method.
	FeedbackBacklogItemFunc func(ctx context.Context, projectDir string, item *domain.BacklogItem, message string) error

	// RecommendWorktreeFunc mocks the RecommendWorktree method.
	RecommendWorktreeFunc func(ctx context.Context, projectDir string, item *domain.BacklogItem) (*domain.Worktree, error)

	// RefineBacklogItemFunc mocks the RefineBacklogItem method.
	RefineBacklogItemFunc func(ctx context.Context, projectDir string, item *domain.BacklogItem) (*domain.BacklogItem, error)

	// StartBacklogItemFunc mocks the StartBacklogItem method.
	StartBacklogItemFunc func(ctx context.Context, projectDir string, item *domain.BacklogItem) error

	// calls tracks calls to the methods.
	calls struct {
		// FeedbackBacklogItem holds details about calls to the FeedbackBacklogItem method.
		FeedbackBacklogItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectDir is the projectDir argument value.
			ProjectDir string
			// Item is the item argument value.
			Item *domain.BacklogItem
			// Message is the message argument value.
			Message string
		}
		// RecommendWorktree holds details about calls to the RecommendWorktree method.
		RecommendWorktree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectDir is the projectDir argument value.
			ProjectDir string
			// Item is the item argument value.
			Item *domain.BacklogItem
		}
		// RefineBacklogItem holds details about calls to the RefineBacklogItem method.
		RefineBacklogItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectDir is the projectDir argument value.
			ProjectDir string
			// Item is the item argument value.
			Item *domain.BacklogItem
		}
		// StartBacklogItem holds details about calls to the StartBacklogItem method.
		StartBacklogItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectDir is the projectDir argument value.
			ProjectDir string
			// Item is the item argument value.
			Item *domain.BacklogItem
		}
	}
	lockFeedbackBacklogItem sync.RWMutex
	lockRecommendWorktree sync.RWMutex
	lockRefineBacklogItem sync.RWMutex
	lockStartBacklogItem  sync.RWMutex
}

// FeedbackBacklogItem calls FeedbackBacklogItemFunc.
func (mock *BacklogActionRunnerMock) FeedbackBacklogItem(
	ctx context.Context,
	projectDir string,
	item *domain.BacklogItem,
	message string,
) error {
	if mock.FeedbackBacklogItemFunc == nil {
		panic("BacklogActionRunnerMock.FeedbackBacklogItemFunc: method is nil but BacklogActionRunner.FeedbackBacklogItem was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
		Message    string
	}{
		Ctx:        ctx,
		ProjectDir: projectDir,
		Item:       item,
		Message:    message,
	}
	mock.lockFeedbackBacklogItem.Lock()
	mock.calls.FeedbackBacklogItem = append(mock.calls.FeedbackBacklogItem, callInfo)
	mock.lockFeedbackBacklogItem.Unlock()
	return mock.FeedbackBacklogItemFunc(ctx, projectDir, item, message)
}

// FeedbackBacklogItemCalls gets all the calls that were made to FeedbackBacklogItem.
// Check the length with:
//
//	len(mockedBacklogActionRunner.FeedbackBacklogItemCalls())
func (mock *BacklogActionRunnerMock) FeedbackBacklogItemCalls() []struct {
	Ctx        context.Context
	ProjectDir string
	Item       *domain.BacklogItem
	Message    string
} {
	var calls []struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
		Message    string
	}
	mock.lockFeedbackBacklogItem.RLock()
	calls = mock.calls.FeedbackBacklogItem
	mock.lockFeedbackBacklogItem.RUnlock()
	return calls
}

// RecommendWorktree calls RecommendWorktreeFunc.
func (mock *BacklogActionRunnerMock) RecommendWorktree(ctx context.Context, projectDir string, item *domain.BacklogItem) (*domain.Worktree, error) {
	if mock.RecommendWorktreeFunc == nil {
		panic("BacklogActionRunnerMock.RecommendWorktreeFunc: method is nil but BacklogActionRunner.RecommendWorktree was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
	}{
		Ctx:        ctx,
		ProjectDir: projectDir,
		Item:       item,
	}
	mock.lockRecommendWorktree.Lock()
	mock.calls.RecommendWorktree = append(mock.calls.RecommendWorktree, callInfo)
	mock.lockRecommendWorktree.Unlock()
	return mock.RecommendWorktreeFunc(ctx, projectDir, item)
}

// RecommendWorktreeCalls gets all the calls that were made to RecommendWorktree.
// Check the length with:
//
//	len(mockedBacklogActionRunner.RecommendWorktreeCalls())
func (mock *BacklogActionRunnerMock) RecommendWorktreeCalls() []struct {
	Ctx        context.Context
	ProjectDir string
	Item       *domain.BacklogItem
} {
	var calls []struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
	}
	mock.lockRecommendWorktree.RLock()
	calls = mock.calls.RecommendWorktree
	mock.lockRecommendWorktree.RUnlock()
	return calls
}

// RefineBacklogItem calls RefineBacklogItemFunc.
func (mock *BacklogActionRunnerMock) RefineBacklogItem(ctx context.Context, projectDir string, item *domain.BacklogItem) (*domain.BacklogItem, error) {
	if mock.RefineBacklogItemFunc == nil {
		panic("BacklogActionRunnerMock.RefineBacklogItemFunc: method is nil but BacklogActionRunner.RefineBacklogItem was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
	}{
		Ctx:        ctx,
		ProjectDir: projectDir,
		Item:       item,
	}
	mock.lockRefineBacklogItem.Lock()
	mock.calls.RefineBacklogItem = append(mock.calls.RefineBacklogItem, callInfo)
	mock.lockRefineBacklogItem.Unlock()
	return mock.RefineBacklogItemFunc(ctx, projectDir, item)
}

// RefineBacklogItemCalls gets all the calls that were made to RefineBacklogItem.
// Check the length with:
//
//	len(mockedBacklogActionRunner.RefineBacklogItemCalls())
func (mock *BacklogActionRunnerMock) RefineBacklogItemCalls() []struct {
	Ctx        context.Context
	ProjectDir string
	Item       *domain.BacklogItem
} {
	var calls []struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
	}
	mock.lockRefineBacklogItem.RLock()
	calls = mock.calls.RefineBacklogItem
	mock.lockRefineBacklogItem.RUnlock()
	return calls
}

// StartBacklogItem calls StartBacklogItemFunc.
func (mock *BacklogActionRunnerMock) StartBacklogItem(ctx context.Context, projectDir string, item *domain.BacklogItem) error {
	if mock.StartBacklogItemFunc == nil {
		panic("BacklogActionRunnerMock.StartBacklogItemFunc: method is nil but BacklogActionRunner.StartBacklogItem was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
	}{
		Ctx:        ctx,
		ProjectDir: projectDir,
		Item:       item,
	}
	mock.lockStartBacklogItem.Lock()
	mock.calls.StartBacklogItem = append(mock.calls.StartBacklogItem, callInfo)
	mock.lockStartBacklogItem.Unlock()
	return mock.StartBacklogItemFunc(ctx, projectDir, item)
}

// StartBacklogItemCalls gets all the calls that were made to StartBacklogItem.
// Check the length with:
//
//	len(mockedBacklogActionRunner.StartBacklogItemCalls())
func (mock *BacklogActionRunnerMock) StartBacklogItemCalls() []struct {
	Ctx        context.Context
	ProjectDir string
	Item       *domain.BacklogItem
} {
	var calls []struct {
		Ctx        context.Context
		ProjectDir string
		Item       *domain.BacklogItem
	}
	mock.lockStartBacklogItem.RLock()
	calls = mock.calls.StartBacklogItem
	mock.lockStartBacklogItem.RUnlock()
	return calls
}
