// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/worker/internal/pkg/domain"
	"sync"
)

// BacklogItemRepositoryMock is a mock implementation of repository.BacklogItemRepository.
//
//	func TestSomethingThatUsesBacklogItemRepository(t *testing.T) {
//
//		// make and configure a mocked repository.BacklogItemRepository
//		mockedBacklogItemRepository := &BacklogItemRepositoryMock{
//			CreateBacklogItemFunc: func(ctx context.Context, item *domain.BacklogItem) error {
//				panic("mock out the CreateBacklogItem method")
//			},
//			GetBacklogItemFunc: func(ctx context.Context, id string) (*domain.BacklogItem, error) {
//				panic("mock out the GetBacklogItem method")
//			},
//			ListBacklogItemsFunc: func(ctx context.Context, projectID string, afterID string, limit int) ([]*domain.BacklogItem, error) {
//				panic("mock out the ListBacklogItems method")
//			},
//			UpdateBacklogItemFunc: func(ctx context.Context, item *domain.BacklogItem) error {
//				panic("mock out the UpdateBacklogItem method")
//			},
//		}
//
//		// use mockedBacklogItemRepository in code that requires repository.BacklogItemRepository
//		// and then make assertions.
//
//	}
type BacklogItemRepositoryMock struct {
	// CreateBacklogItemFunc mocks the CreateBacklogItem method.
	CreateBacklogItemFunc func(ctx context.Context, item *domain.BacklogItem) error

	// GetBacklogItemFunc mocks the GetBacklogItem method.
	GetBacklogItemFunc func(ctx context.Context, id string) (*domain.BacklogItem, error)

	// ListBacklogItemsFunc mocks the ListBacklogItems method.
	ListBacklogItemsFunc func(ctx context.Context, projectID string, afterID string, limit int) ([]*domain.BacklogItem, error)

	// UpdateBacklogItemFunc mocks the UpdateBacklogItem method.
	UpdateBacklogItemFunc func(ctx context.Context, item *domain.BacklogItem) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBacklogItem holds details about calls to the CreateBacklogItem method.
		CreateBacklogItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item *domain.BacklogItem
		}
		// GetBacklogItem holds details about calls to the GetBacklogItem method.
		GetBacklogItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// ListBacklogItems holds details about calls to the ListBacklogItems method.
		ListBacklogItems []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// AfterID is the afterID argument value.
			AfterID string
			// Limit is the limit argument value.
			Limit int
		}
		// UpdateBacklogItem holds details about calls to the UpdateBacklogItem method.
		UpdateBacklogItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item *domain.BacklogItem
		}
	}
	lockCreateBacklogItem sync.RWMutex
	lockGetBacklogItem    sync.RWMutex
	lockListBacklogItems  sync.RWMutex
	lockUpdateBacklogItem sync.RWMutex
}

// CreateBacklogItem calls CreateBacklogItemFunc.
func (mock *BacklogItemRepositoryMock) CreateBacklogItem(ctx context.Context, item *domain.BacklogItem) error {
	if mock.CreateBacklogItemFunc == nil {
		panic("BacklogItemRepositoryMock.CreateBacklogItemFunc: method is nil but BacklogItemRepository.CreateBacklogItem was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Item *domain.BacklogItem
	}{
		Ctx:  ctx,
		Item: item,
	}
	mock.lockCreateBacklogItem.Lock()
	mock.calls.CreateBacklogItem = append(mock.calls.CreateBacklogItem, callInfo)
	mock.lockCreateBacklogItem.Unlock()
	return mock.CreateBacklogItemFunc(ctx, item)
}

// CreateBacklogItemCalls gets all the calls that were made to CreateBacklogItem.
// Check the length with:
//
//	len(mockedBacklogItemRepository.CreateBacklogItemCalls())
func (mock *BacklogItemRepositoryMock) CreateBacklogItemCalls() []struct {
	Ctx  context.Context
	Item *domain.BacklogItem
} {
	var calls []struct {
		Ctx  context.Context
		Item *domain.BacklogItem
	}
	mock.lockCreateBacklogItem.RLock()
	calls = mock.calls.CreateBacklogItem
	mock.lockCreateBacklogItem.RUnlock()
	return calls
}

// GetBacklogItem calls GetBacklogItemFunc.
func (mock *BacklogItemRepositoryMock) GetBacklogItem(ctx context.Context, id string) (*domain.BacklogItem, error) {
	if mock.GetBacklogItemFunc == nil {
		panic("BacklogItemRepositoryMock.GetBacklogItemFunc: method is nil but BacklogItemRepository.GetBacklogItem was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetBacklogItem.Lock()
	mock.calls.GetBacklogItem = append(mock.calls.GetBacklogItem, callInfo)
	mock.lockGetBacklogItem.Unlock()
	return mock.GetBacklogItemFunc(ctx, id)
}

// GetBacklogItemCalls gets all the calls that were made to GetBacklogItem.
// Check the length with:
//
//	len(mockedBacklogItemRepository.GetBacklogItemCalls())
func (mock *BacklogItemRepositoryMock) GetBacklogItemCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetBacklogItem.RLock()
	calls = mock.calls.GetBacklogItem
	mock.lockGetBacklogItem.RUnlock()
	return calls
}

// ListBacklogItems calls ListBacklogItemsFunc.
func (mock *BacklogItemRepositoryMock) ListBacklogItems(ctx context.Context, projectID string, afterID string, limit int) ([]*domain.BacklogItem, error) {
	if mock.ListBacklogItemsFunc == nil {
		panic("BacklogItemRepositoryMock.ListBacklogItemsFunc: method is nil but BacklogItemRepository.ListBacklogItems was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		AfterID   string
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		AfterID:   afterID,
		Limit:     limit,
	}
	mock.lockListBacklogItems.Lock()
	mock.calls.ListBacklogItems = append(mock.calls.ListBacklogItems, callInfo)
	mock.lockListBacklogItems.Unlock()
	return mock.ListBacklogItemsFunc(ctx, projectID, afterID, limit)
}

// ListBacklogItemsCalls gets all the calls that were made to ListBacklogItems.
// Check the length with:
//
//	len(mockedBacklogItemRepository.ListBacklogItemsCalls())
func (mock *BacklogItemRepositoryMock) ListBacklogItemsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	AfterID   string
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		AfterID   string
		Limit     int
	}
	mock.lockListBacklogItems.RLock()
	calls = mock.calls.ListBacklogItems
	mock.lockListBacklogItems.RUnlock()
	return calls
}

// UpdateBacklogItem calls UpdateBacklogItemFunc.
func (mock *BacklogItemRepositoryMock) UpdateBacklogItem(ctx context.Context, item *domain.BacklogItem) error {
	if mock.UpdateBacklogItemFunc == nil {
		panic("BacklogItemRepositoryMock.UpdateBacklogItemFunc: method is nil but BacklogItemRepository.UpdateBacklogItem was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Item *domain.BacklogItem
	}{
		Ctx:  ctx,
		Item: item,
	}
	mock.lockUpdateBacklogItem.Lock()
	mock.calls.UpdateBacklogItem = append(mock.calls.UpdateBacklogItem, callInfo)
	mock.lockUpdateBacklogItem.Unlock()
	return mock.UpdateBacklogItemFunc(ctx, item)
}

// UpdateBacklogItemCalls gets all the calls that were made to UpdateBacklogItem.
// Check the length with:
//
//	len(mockedBacklogItemRepository.UpdateBacklogItemCalls())
func (mock *BacklogItemRepositoryMock) UpdateBacklogItemCalls() []struct {
	Ctx  context.Context
	Item *domain.BacklogItem
} {
	var calls []struct {
		Ctx  context.Context
		Item *domain.BacklogItem
	}
	mock.lockUpdateBacklogItem.RLock()
	calls = mock.calls.UpdateBacklogItem
	mock.lockUpdateBacklogItem.RUnlock()
	return calls
}
