// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/worker/internal/pkg/domain"
	"sync"
)

// BacklogItemRepositoryMock is a mock implementation of repository.BacklogItemRepository.
//
//	func TestSomethingThatUsesBacklogItemRepository(t *testing.T) {
//
//		// make and configure a mocked repository.BacklogItemRepository
//		mockedBacklogItemRepository := &BacklogItemRepositoryMock{
//			CreateBacklogItemFunc: func(ctx context.Context, item *domain.BacklogItem) error {
//				panic("mock out the CreateBacklogItem method")
//			},
//			ListBacklogItemsFunc: func(ctx context.Context, projectID string, afterID string, limit int) ([]*domain.BacklogItem, error) {
//				panic("mock out the ListBacklogItems method")
//			},
//		}
//
//		// use mockedBacklogItemRepository in code that requires repository.BacklogItemRepository
//		// and then make assertions.
//
//	}
type BacklogItemRepositoryMock struct {
	// CreateBacklogItemFunc mocks the CreateBacklogItem method.
	CreateBacklogItemFunc func(ctx context.Context, item *domain.BacklogItem) error

	// ListBacklogItemsFunc mocks the ListBacklogItems method.
	ListBacklogItemsFunc func(ctx context.Context, projectID string, afterID string, limit int) ([]*domain.BacklogItem, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateBacklogItem holds details about calls to the CreateBacklogItem method.
		CreateBacklogItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item *domain.BacklogItem
		}
		// ListBacklogItems holds details about calls to the ListBacklogItems method.
		ListBacklogItems []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// AfterID is the afterID argument value.
			AfterID string
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockCreateBacklogItem sync.RWMutex
	lockListBacklogItems  sync.RWMutex
}

// CreateBacklogItem calls CreateBacklogItemFunc.
func (mock *BacklogItemRepositoryMock) CreateBacklogItem(ctx context.Context, item *domain.BacklogItem) error {
	if mock.CreateBacklogItemFunc == nil {
		panic("BacklogItemRepositoryMock.CreateBacklogItemFunc: method is nil but BacklogItemRepository.CreateBacklogItem was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Item *domain.BacklogItem
	}{
		Ctx:  ctx,
		Item: item,
	}
	mock.lockCreateBacklogItem.Lock()
	mock.calls.CreateBacklogItem = append(mock.calls.CreateBacklogItem, callInfo)
	mock.lockCreateBacklogItem.Unlock()
	return mock.CreateBacklogItemFunc(ctx, item)
}

// CreateBacklogItemCalls gets all the calls that were made to CreateBacklogItem.
// Check the length with:
//
//	len(mockedBacklogItemRepository.CreateBacklogItemCalls())
func (mock *BacklogItemRepositoryMock) CreateBacklogItemCalls() []struct {
	Ctx  context.Context
	Item *domain.BacklogItem
} {
	var calls []struct {
		Ctx  context.Context
		Item *domain.BacklogItem
	}
	mock.lockCreateBacklogItem.RLock()
	calls = mock.calls.CreateBacklogItem
	mock.lockCreateBacklogItem.RUnlock()
	return calls
}

// ListBacklogItems calls ListBacklogItemsFunc.
func (mock *BacklogItemRepositoryMock) ListBacklogItems(ctx context.Context, projectID string, afterID string, limit int) ([]*domain.BacklogItem, error) {
	if mock.ListBacklogItemsFunc == nil {
		panic("BacklogItemRepositoryMock.ListBacklogItemsFunc: method is nil but BacklogItemRepository.ListBacklogItems was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		AfterID   string
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		AfterID:   afterID,
		Limit:     limit,
	}
	mock.lockListBacklogItems.Lock()
	mock.calls.ListBacklogItems = append(mock.calls.ListBacklogItems, callInfo)
	mock.lockListBacklogItems.Unlock()
	return mock.ListBacklogItemsFunc(ctx, projectID, afterID, limit)
}

// ListBacklogItemsCalls gets all the calls that were made to ListBacklogItems.
// Check the length with:
//
//	len(mockedBacklogItemRepository.ListBacklogItemsCalls())
func (mock *BacklogItemRepositoryMock) ListBacklogItemsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	AfterID   string
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		AfterID   string
		Limit     int
	}
	mock.lockListBacklogItems.RLock()
	calls = mock.calls.ListBacklogItems
	mock.lockListBacklogItems.RUnlock()
	return calls
}
