// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/worker/internal/pkg/domain"
	"sync"
)

// ProjectRepositoryMock is a mock implementation of repository.ProjectRepository.
//
//	func TestSomethingThatUsesProjectRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ProjectRepository
//		mockedProjectRepository := &ProjectRepositoryMock{
//			CreateFunc: func(ctx context.Context, project *domain.Project) error {
//				panic("mock out the Create method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (*domain.Project, error) {
//				panic("mock out the GetByName method")
//			},
//			ListFunc: func(ctx context.Context) ([]*domain.Project, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedProjectRepository in code that requires repository.ProjectRepository
//		// and then make assertions.
//
//	}
type ProjectRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, project *domain.Project) error

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (*domain.Project, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]*domain.Project, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Project is the project argument value.
			Project *domain.Project
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCreate    sync.RWMutex
	lockGetByName sync.RWMutex
	lockList      sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ProjectRepositoryMock) Create(ctx context.Context, project *domain.Project) error {
	if mock.CreateFunc == nil {
		panic("ProjectRepositoryMock.CreateFunc: method is nil but ProjectRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Project *domain.Project
	}{
		Ctx:     ctx,
		Project: project,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, project)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedProjectRepository.CreateCalls())
func (mock *ProjectRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	Project *domain.Project
} {
	var calls []struct {
		Ctx     context.Context
		Project *domain.Project
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *ProjectRepositoryMock) GetByName(ctx context.Context, name string) (*domain.Project, error) {
	if mock.GetByNameFunc == nil {
		panic("ProjectRepositoryMock.GetByNameFunc: method is nil but ProjectRepository.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedProjectRepository.GetByNameCalls())
func (mock *ProjectRepositoryMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ProjectRepositoryMock) List(ctx context.Context) ([]*domain.Project, error) {
	if mock.ListFunc == nil {
		panic("ProjectRepositoryMock.ListFunc: method is nil but ProjectRepository.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedProjectRepository.ListCalls())
func (mock *ProjectRepositoryMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
