// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/worker/internal/pkg/domain"
	"sync"
)

// ProjectRepositoryMock is a mock implementation of repository.ProjectRepository.
//
//	func TestSomethingThatUsesProjectRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ProjectRepository
//		mockedProjectRepository := &ProjectRepositoryMock{
//			CreateProjectFunc: func(ctx context.Context, project *domain.Project) error {
//				panic("mock out the CreateProject method")
//			},
//			GetProjectByNameFunc: func(ctx context.Context, name string) (*domain.Project, error) {
//				panic("mock out the GetProjectByName method")
//			},
//			ListProjectsFunc: func(ctx context.Context) ([]*domain.Project, error) {
//				panic("mock out the ListProjects method")
//			},
//		}
//
//		// use mockedProjectRepository in code that requires repository.ProjectRepository
//		// and then make assertions.
//
//	}
type ProjectRepositoryMock struct {
	// CreateProjectFunc mocks the CreateProject method.
	CreateProjectFunc func(ctx context.Context, project *domain.Project) error

	// GetProjectByNameFunc mocks the GetProjectByName method.
	GetProjectByNameFunc func(ctx context.Context, name string) (*domain.Project, error)

	// ListProjectsFunc mocks the ListProjects method.
	ListProjectsFunc func(ctx context.Context) ([]*domain.Project, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateProject holds details about calls to the CreateProject method.
		CreateProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Project is the project argument value.
			Project *domain.Project
		}
		// GetProjectByName holds details about calls to the GetProjectByName method.
		GetProjectByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ListProjects holds details about calls to the ListProjects method.
		ListProjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCreateProject sync.RWMutex
	lockGetProjectByName sync.RWMutex
	lockListProjects     sync.RWMutex
}

// CreateProject calls CreateProjectFunc.
func (mock *ProjectRepositoryMock) CreateProject(ctx context.Context, project *domain.Project) error {
	if mock.CreateProjectFunc == nil {
		panic("ProjectRepositoryMock.CreateProjectFunc: method is nil but ProjectRepository.CreateProject was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Project *domain.Project
	}{
		Ctx:     ctx,
		Project: project,
	}
	mock.lockCreateProject.Lock()
	mock.calls.CreateProject = append(mock.calls.CreateProject, callInfo)
	mock.lockCreateProject.Unlock()
	return mock.CreateProjectFunc(ctx, project)
}

// CreateProjectCalls gets all the calls that were made to CreateProject.
// Check the length with:
//
//	len(mockedProjectRepository.CreateProjectCalls())
func (mock *ProjectRepositoryMock) CreateProjectCalls() []struct {
	Ctx     context.Context
	Project *domain.Project
} {
	var calls []struct {
		Ctx     context.Context
		Project *domain.Project
	}
	mock.lockCreateProject.RLock()
	calls = mock.calls.CreateProject
	mock.lockCreateProject.RUnlock()
	return calls
}

// GetProjectByName calls GetProjectByNameFunc.
func (mock *ProjectRepositoryMock) GetProjectByName(ctx context.Context, name string) (*domain.Project, error) {
	if mock.GetProjectByNameFunc == nil {
		panic("ProjectRepositoryMock.GetProjectByNameFunc: method is nil but ProjectRepository.GetProjectByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetProjectByName.Lock()
	mock.calls.GetProjectByName = append(mock.calls.GetProjectByName, callInfo)
	mock.lockGetProjectByName.Unlock()
	return mock.GetProjectByNameFunc(ctx, name)
}

// GetProjectByNameCalls gets all the calls that were made to GetProjectByName.
// Check the length with:
//
//	len(mockedProjectRepository.GetProjectByNameCalls())
func (mock *ProjectRepositoryMock) GetProjectByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetProjectByName.RLock()
	calls = mock.calls.GetProjectByName
	mock.lockGetProjectByName.RUnlock()
	return calls
}

// ListProjects calls ListProjectsFunc.
func (mock *ProjectRepositoryMock) ListProjects(ctx context.Context) ([]*domain.Project, error) {
	if mock.ListProjectsFunc == nil {
		panic("ProjectRepositoryMock.ListProjectsFunc: method is nil but ProjectRepository.ListProjects was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListProjects.Lock()
	mock.calls.ListProjects = append(mock.calls.ListProjects, callInfo)
	mock.lockListProjects.Unlock()
	return mock.ListProjectsFunc(ctx)
}

// ListProjectsCalls gets all the calls that were made to ListProjects.
// Check the length with:
//
//	len(mockedProjectRepository.ListProjectsCalls())
func (mock *ProjectRepositoryMock) ListProjectsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListProjects.RLock()
	calls = mock.calls.ListProjects
	mock.lockListProjects.RUnlock()
	return calls
}
