// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/worker/internal/pkg/domain"
	"sync"
)

// WorkspaceMock is a mock implementation of workspace.Workspace.
//
//	func TestSomethingThatUsesWorkspace(t *testing.T) {
//
//		// make and configure a mocked workspace.Workspace
//		mockedWorkspace := &WorkspaceMock{
//			CreateWorkspaceFunc: func(ctx context.Context, project *domain.Project) error {
//				panic("mock out the CreateWorkspace method")
//			},
//		}
//
//		// use mockedWorkspace in code that requires workspace.Workspace
//		// and then make assertions.
//
//	}
type WorkspaceMock struct {
	// CreateWorkspaceFunc mocks the CreateWorkspace method.
	CreateWorkspaceFunc func(ctx context.Context, project *domain.Project) error
	// ProjectDirFunc mocks the ProjectDir method.
	ProjectDirFunc func(ctx context.Context, project *domain.Project) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateWorkspace holds details about calls to the CreateWorkspace method.
		CreateWorkspace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Project is the project argument value.
			Project *domain.Project
		}
		// ProjectDir holds details about calls to the ProjectDir method.
		ProjectDir []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Project is the project argument value.
			Project *domain.Project
		}
	}
	lockCreateWorkspace sync.RWMutex
	lockProjectDir      sync.RWMutex
}

// CreateWorkspace calls CreateWorkspaceFunc.
func (mock *WorkspaceMock) CreateWorkspace(ctx context.Context, project *domain.Project) error {
	if mock.CreateWorkspaceFunc == nil {
		panic("WorkspaceMock.CreateWorkspaceFunc: method is nil but Workspace.CreateWorkspace was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Project *domain.Project
	}{
		Ctx:     ctx,
		Project: project,
	}
	mock.lockCreateWorkspace.Lock()
	mock.calls.CreateWorkspace = append(mock.calls.CreateWorkspace, callInfo)
	mock.lockCreateWorkspace.Unlock()
	return mock.CreateWorkspaceFunc(ctx, project)
}

// CreateWorkspaceCalls gets all the calls that were made to CreateWorkspace.
// Check the length with:
//
//	len(mockedWorkspace.CreateWorkspaceCalls())
func (mock *WorkspaceMock) CreateWorkspaceCalls() []struct {
	Ctx     context.Context
	Project *domain.Project
} {
	var calls []struct {
		Ctx     context.Context
		Project *domain.Project
	}
	mock.lockCreateWorkspace.RLock()
	calls = mock.calls.CreateWorkspace
	mock.lockCreateWorkspace.RUnlock()
	return calls
}

// ProjectDir calls ProjectDirFunc.
func (mock *WorkspaceMock) ProjectDir(ctx context.Context, project *domain.Project) (string, error) {
	if mock.ProjectDirFunc == nil {
		panic("WorkspaceMock.ProjectDirFunc: method is nil but Workspace.ProjectDir was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Project *domain.Project
	}{
		Ctx:     ctx,
		Project: project,
	}
	mock.lockProjectDir.Lock()
	mock.calls.ProjectDir = append(mock.calls.ProjectDir, callInfo)
	mock.lockProjectDir.Unlock()
	return mock.ProjectDirFunc(ctx, project)
}

// ProjectDirCalls gets all the calls that were made to ProjectDir.
// Check the length with:
//
//	len(mockedWorkspace.ProjectDirCalls())
func (mock *WorkspaceMock) ProjectDirCalls() []struct {
	Ctx     context.Context
	Project *domain.Project
} {
	var calls []struct {
		Ctx     context.Context
		Project *domain.Project
	}
	mock.lockProjectDir.RLock()
	calls = mock.calls.ProjectDir
	mock.lockProjectDir.RUnlock()
	return calls
}
