// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/worker/internal/pkg/domain"
	"sync"
)

// WorkspaceMock is a mock implementation of workspacer.Workspacer.
//
//	func TestSomethingThatUsesWorkspace(t *testing.T) {
//
//		// make and configure a mocked workspacer.Workspacer
//		mockedWorkspace := &WorkspaceMock{
//			PrepareWorkspaceFunc: func(ctx context.Context, project *domain.Project) error {
//				panic("mock out the PrepareWorkspace method")
//			},
//		}
//
//		// use mockedWorkspace in code that requires workspacer.Workspacer
//		// and then make assertions.
//
//	}
type WorkspaceMock struct {
	// PrepareWorkspaceFunc mocks the PrepareWorkspace method.
	PrepareWorkspaceFunc func(ctx context.Context, project *domain.Project) (*domain.Workspace, error)

	// calls tracks calls to the methods.
	calls struct {
		// PrepareWorkspace holds details about calls to the PrepareWorkspace method.
		PrepareWorkspace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Project is the project argument value.
			Project *domain.Project
		}
	}
	lockPrepareWorkspace sync.RWMutex
}

// PrepareWorkspace calls PrepareWorkspaceFunc.
func (mock *WorkspaceMock) PrepareWorkspace(ctx context.Context, project *domain.Project) (*domain.Workspace, error) {
	if mock.PrepareWorkspaceFunc == nil {
		panic("WorkspaceMock.PrepareWorkspaceFunc: method is nil but Workspacer.PrepareWorkspace was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Project *domain.Project
	}{
		Ctx:     ctx,
		Project: project,
	}
	mock.lockPrepareWorkspace.Lock()
	mock.calls.PrepareWorkspace = append(mock.calls.PrepareWorkspace, callInfo)
	mock.lockPrepareWorkspace.Unlock()
	return mock.PrepareWorkspaceFunc(ctx, project)
}

// PrepareWorkspaceCalls gets all the calls that were made to PrepareWorkspace.
// Check the length with:
//
//	len(mockedWorkspace.PrepareWorkspaceCalls())
func (mock *WorkspaceMock) PrepareWorkspaceCalls() []struct {
	Ctx     context.Context
	Project *domain.Project
} {
	var calls []struct {
		Ctx     context.Context
		Project *domain.Project
	}
	mock.lockPrepareWorkspace.RLock()
	calls = mock.calls.PrepareWorkspace
	mock.lockPrepareWorkspace.RUnlock()
	return calls
}
